# Generated by Django 6.0.2 on 2026-02-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tecnologia', models.CharField(max_length=100)),
                ('seniority', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
