# Generated by Django 6.0.2 on 2026-02-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
